apiVersion: v1
kind: Service
metadata:
  name: fms-db-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: fms-db
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fms-db
spec:
  selector:
    matchLabels:
      app: fms-db
  replicas: 1
  template:
    metadata:
      labels:
        app: fms-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: mongo:7.0.4
          name: fms-db
          command:
            - mongod
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
              name: fms-db
          volumeMounts:
            - name: volume
              mountPath: /data/db
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: fms-db-volume

---


---
apiVersion: v1
kind: Service
metadata:
  name: rm-db-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: rm-db
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rm-db
spec:
  selector:
    matchLabels:
      app: rm-db
  replicas: 1
  template:
    metadata:
      labels:
        app: rm-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: mongo:7.0.4
          name: rm-db
          command:
            - mongod
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
              name: rm-db
          volumeMounts:
            - name: volume1
              mountPath: /data/db
      volumes:
        - name: volume1
          persistentVolumeClaim:
            claimName: rm-db-volume
